"""initial schema

Revision ID: 331c6df8e192
Revises: 
Create Date: 2026-09-07 22:16:54.644983
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '331c6df8e192'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('cash', 'bank', 'credit_card', 'emoney', 'prepaid', name='account_type', native_enum=False), nullable=False),
    sa.Column('institution', sa.String(length=128), nullable=True),
    sa.Column('opening_balance', sa.Integer(), nullable=False),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('closing_day', sa.Integer(), nullable=True),
    sa.Column('payment_day', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('expense', 'income', name='category_type', native_enum=False), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('user_id', 'key', name='uq_categories_user_key')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_user_id'), ['user_id'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('manual', 'screenshot', 'csv', 'recurring', name='batch_source', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('draft', 'confirmed', 'discarded', name='batch_status', native_enum=False), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_import_batches_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_user_id'), ['user_id'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings')),
    sa.UniqueConstraint('user_id', 'key', name='uq_settings_user_key')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_user_id'), ['user_id'], unique=False)

    op.create_table('balance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('computed_balance', sa.Integer(), nullable=True),
    sa.Column('diff', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'ocr', name='snapshot_source', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_balance_snapshots_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_balance_snapshots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_balance_snapshots'))
    )
    with op.batch_alter_table('balance_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_snapshots_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_balance_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('alert_threshold_pct', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_budgets_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_budgets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets')),
    sa.UniqueConstraint('user_id', 'category_id', 'year_month', name='uq_budgets_user_cat_month')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_user_id'), ['user_id'], unique=False)

    op.create_table('category_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_category_names_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_names')),
    sa.UniqueConstraint('category_id', 'locale', name='uq_category_names_category_locale')
    )
    with op.batch_alter_table('category_names', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_names_category_id'), ['category_id'], unique=False)

    op.create_table('category_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.Enum('exact', 'contains', 'regex', name='match_type', native_enum=False), nullable=False),
    sa.Column('pattern', sa.String(length=512), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_category_rules_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_category_rules_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_category_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_rules'))
    )
    with op.batch_alter_table('category_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_rules_user_id'), ['user_id'], unique=False)

    op.create_table('import_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('detected_institution', sa.String(length=64), nullable=True),
    sa.Column('ocr_provider', sa.String(length=32), nullable=True),
    sa.Column('ocr_raw_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_images_batch_id_import_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_images'))
    )
    with op.batch_alter_table('import_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_images_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_images_sha256'), ['sha256'], unique=False)

    op.create_table('merchant_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('merchant_norm', sa.String(length=512), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_merchant_memory_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_merchant_memory_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_memory')),
    sa.UniqueConstraint('user_id', 'merchant_norm', name='uq_merchant_memory_user_merchant')
    )
    with op.batch_alter_table('merchant_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchant_memory_user_id'), ['user_id'], unique=False)

    op.create_table('recurring_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.Enum('expense', 'income', 'transfer_out', 'transfer_in', name='recurring_direction', native_enum=False), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('amount_is_variable', sa.Boolean(), nullable=False),
    sa.Column('freq', sa.Enum('monthly', 'bimonthly', 'yearly', name='recurring_freq', native_enum=False), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('months', sa.String(length=32), nullable=True),
    sa.Column('mode', sa.Enum('auto', 'remind', name='recurring_mode', native_enum=False), nullable=False),
    sa.Column('reminder_days', sa.Integer(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('last_generated_at', sa.Date(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_recurring_rules_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_recurring_rules_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recurring_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurring_rules'))
    )
    with op.batch_alter_table('recurring_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_rules_next_due_date'), ['next_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_rules_user_id'), ['user_id'], unique=False)

    op.create_table('staged_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('source_image_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('direction', sa.Enum('expense', 'income', 'transfer_out', 'transfer_in', name='staged_direction', native_enum=False), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('merchant_raw', sa.String(length=512), nullable=False),
    sa.Column('merchant_norm', sa.String(length=512), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('category_confidence', sa.Float(), nullable=False),
    sa.Column('category_source', sa.Enum('rule', 'memory', 'dictionary', 'llm', 'none', name='category_source', native_enum=False), nullable=False),
    sa.Column('date_inferred', sa.Boolean(), nullable=False),
    sa.Column('dup_status', sa.Enum('none', 'merged', 'duplicate', 'maybe', name='dup_status', native_enum=False), nullable=False),
    sa.Column('dup_reason', sa.Text(), nullable=True),
    sa.Column('dup_ref_id', sa.Integer(), nullable=True),
    sa.Column('merged_count', sa.Integer(), nullable=False),
    sa.Column('bbox', sa.String(length=64), nullable=True),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('exclude_reason', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_staged_transactions_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_staged_transactions_batch_id_import_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_staged_transactions_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_image_id'], ['import_images.id'], name=op.f('fk_staged_transactions_source_image_id_import_images'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_staged_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staged_transactions'))
    )
    with op.batch_alter_table('staged_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staged_transactions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staged_transactions_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_staged_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('direction', sa.Enum('expense', 'income', 'transfer_out', 'transfer_in', name='direction', native_enum=False), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('merchant_raw', sa.String(length=512), nullable=False),
    sa.Column('merchant_norm', sa.String(length=512), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'screenshot', 'csv', 'recurring', name='txn_source', native_enum=False), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('source_image_id', sa.Integer(), nullable=True),
    sa.Column('recurring_rule_id', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.String(length=40), nullable=False),
    sa.Column('transfer_group_id', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_transactions_amount_non_negative')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transactions_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transactions_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], name=op.f('fk_transactions_import_batch_id_import_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recurring_rule_id'], ['recurring_rules.id'], name=op.f('fk_transactions_recurring_rule_id_recurring_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_image_id'], ['import_images.id'], name=op.f('fk_transactions_source_image_id_import_images'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_transactions_fingerprint', ['fingerprint'], unique=False)
        batch_op.create_index('ix_transactions_merchant_norm', ['merchant_norm'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transfer_group_id'), ['transfer_group_id'], unique=False)
        batch_op.create_index('ix_transactions_user_date', ['user_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index('ix_transactions_user_date')
        batch_op.drop_index(batch_op.f('ix_transactions_transfer_group_id'))
        batch_op.drop_index('ix_transactions_merchant_norm')
        batch_op.drop_index('ix_transactions_fingerprint')
        batch_op.drop_index(batch_op.f('ix_transactions_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_category_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('staged_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staged_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_staged_transactions_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_staged_transactions_batch_id'))

    op.drop_table('staged_transactions')
    with op.batch_alter_table('recurring_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_rules_user_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_rules_next_due_date'))

    op.drop_table('recurring_rules')
    with op.batch_alter_table('merchant_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchant_memory_user_id'))

    op.drop_table('merchant_memory')
    with op.batch_alter_table('import_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_images_sha256'))
        batch_op.drop_index(batch_op.f('ix_import_images_batch_id'))

    op.drop_table('import_images')
    with op.batch_alter_table('category_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_rules_user_id'))

    op.drop_table('category_rules')
    with op.batch_alter_table('category_names', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_names_category_id'))

    op.drop_table('category_names')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_user_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('balance_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balance_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_balance_snapshots_account_id'))

    op.drop_table('balance_snapshots')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_user_id'))

    op.drop_table('settings')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_user_id'))

    op.drop_table('import_batches')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_user_id'))
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))

    op.drop_table('categories')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_user_id'))

    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
