"""staging pipeline fields

Revision ID: 0c87c4d9854b
Revises: 795af5a44926
Create Date: 2026-09-14 23:22:14.090497
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0c87c4d9854b'
down_revision: Union[str, None] = '795af5a44926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_images', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)

    with op.batch_alter_table('staged_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('merged_into_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('balance_after', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transfer_hint', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('counterpart_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_staged_transactions_counterpart_account_id_accounts'), 'accounts', ['counterpart_account_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staged_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_staged_transactions_counterpart_account_id_accounts'), type_='foreignkey')
        batch_op.drop_column('counterpart_account_id')
        batch_op.drop_column('transfer_hint')
        batch_op.drop_column('balance_after')
        batch_op.drop_column('merged_into_id')
        batch_op.drop_column('raw_text')

    with op.batch_alter_table('import_images', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)

    # ### end Alembic commands ###
