"""installment fields

Revision ID: 795af5a44926
Revises: 331c6df8e192
Create Date: 2026-09-07 22:57:49.655251
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '795af5a44926'
down_revision: Union[str, None] = '331c6df8e192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staged_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installment_current', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('installment_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('installment_total_amount', sa.Integer(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installment_current', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('installment_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('installment_total_amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('installment_total_amount')
        batch_op.drop_column('installment_total')
        batch_op.drop_column('installment_current')

    with op.batch_alter_table('staged_transactions', schema=None) as batch_op:
        batch_op.drop_column('installment_total_amount')
        batch_op.drop_column('installment_total')
        batch_op.drop_column('installment_current')

    # ### end Alembic commands ###
